spring:
  mail:
    host:  smtp.gmail.com
    port: 587
    username: jhasujeetkumar95@gmail.com
    password: rewo gwxr zbko ukft
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

